# Generated by Django 3.2.16 on 2024-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='application status')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'application status',
                'verbose_name_plural': 'application statuses',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='direction')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'direction',
                'verbose_name_plural': 'directions',
            },
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='event status')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'event status',
                'verbose_name_plural': 'event statuses',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='format')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'format',
                'verbose_name_plural': 'formats',
            },
        ),
    ]
