# Generated by Django 3.2.16 on 2024-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20240406_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
