# Generated by Django 3.2.16 on 2024-04-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20240407_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='time',
            new_name='date_time',
        ),
    ]
