# Generated by Django 3.2.16 on 2024-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20240409_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Москва', max_length=64, verbose_name='city of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
