MAX_EVENT_LIMIT = 10000
MAX_NAME_LIMIT = 128
MAX_SLUG_LIMIT = 128
MAX_ADDRESS_LIMIT = 1024
MAX_LINK_LIMIT = 1024
MAX_SECTION_LIMIT = 100

DEFAULT_EVENT_STATUS_SLUG = 'registration'
DEFAULT_EVENT_STATUS_NAME = 'Регистрация'

DEFAULT_APPLICATION_STATUS_SLUG = 'sent'
DEFAULT_APPLICATION_STATUS_NAME = 'Отправлена'

MAX_LENGTH_COLOR = 16